### ISSUE TITLE
Incompatability with Rim war

### ISSUE THREAD

**Issue by GitBurner3000** [biomes-team/BiomesCore#6]
There appears to be some sort of an issue with the interaction between caravan generation wrapper in Biomes Core and rim-war
On version 1.4.3704 with a minimal mod list

Harmony
Core +3DLC
Hugslib
Biomes Core
Rimwar

Description:
Rim war has caravans on the world map, you can interact with them it either initiates combat on some map (for a hostile faction) or opens a GUI with options (for a neutral or friendly faction). Neither of these things occur while both mods are active.
However, interactions (Gui or otherwise) with non trader world map units work just fine the problem is strictly for the traders
Also of note this issue was not present when I was using both mods in Version 1.3

Bug log:
Attacking a hostile caravan

Exception while generating pawn group: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at BiomesCore.Patches.PawnGroupKindWorker_Trader_GenerateCarriers.GetExtendedCarriers (System.Collections.Generic.List`1[T] originalCarriers, RimWorld.PawnGroupMakerParms parms) [0x000f7] in <afad0cf4ff2c4e1c82dc8c076b79b6d8>:0 
  at (wrapper dynamic-method) RimWorld.PawnGroupKindWorker_Trader.RimWorld.PawnGroupKindWorker_Trader.GenerateCarriers_Patch0(RimWorld.PawnGroupKindWorker_Trader,RimWorld.PawnGroupMakerParms,RimWorld.PawnGroupMaker,Verse.Pawn,System.Collections.Generic.List`1<Verse.Thing>,System.Collections.Generic.List`1<Verse.Pawn>)
  at RimWorld.PawnGroupKindWorker_Trader.GeneratePawns (RimWorld.PawnGroupMakerParms parms, RimWorld.PawnGroupMaker groupMaker, System.Collections.Generic.List`1[T] outPawns, System.Boolean errorOnZeroResults) [0x00223] in <95de19971c5d40878d8742747904cdcd>:0 
  at RimWorld.PawnGroupKindWorker.GeneratePawns (RimWorld.PawnGroupMakerParms parms, RimWorld.PawnGroupMaker groupMaker, System.Boolean errorOnZeroResults) [0x00011] in <95de19971c5d40878d8742747904cdcd>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
RimWorld.PawnGroupKindWorker:GeneratePawns (RimWorld.PawnGroupMakerParms,RimWorld.PawnGroupMaker,bool)
RimWorld.PawnGroupMaker:GeneratePawns (RimWorld.PawnGroupMakerParms,bool)
RimWorld.PawnGroupMakerUtility/<GeneratePawns>d__2:MoveNext ()
System.Collections.Generic.List`1<Verse.Pawn>:.ctor (System.Collections.Generic.IEnumerable`1<Verse.Pawn>)
System.Linq.Enumerable:ToList<Verse.Pawn> (System.Collections.Generic.IEnumerable`1<Verse.Pawn>)
RimWar.Utility.IncidentWorker_WarObjectMeeting:GenerateCaravanPawns (RimWorld.Faction,int)
RimWar.Utility.IncidentWorker_WarObjectMeeting:TryExecuteWorker (RimWorld.IncidentParms)
RimWar.Utility.IncidentWorker_WarObjectMeeting:PreExecuteWorker (RimWorld.IncidentParms,RimWar.Planet.WarObject,int)
RimWar.Planet.IncidentUtility:DoCaravanAttackWithPoints (RimWar.Planet.WarObject,RimWorld.Planet.Caravan,RimWar.RimWarData,RimWorld.PawnsArrivalModeDef,RimWorld.PawnGroupKindDef)
RimWar.Planet.WarObject:EngageCaravan (RimWorld.Planet.Caravan)
RimWar.Planet.CaravanArrivalAction_AttackWarObject:Arrived (RimWorld.Planet.Caravan)
RimWorld.Planet.Caravan_PathFollower:PatherArrived ()
(wrapper dynamic-method) RimWorld.Planet.Caravan_PathFollower:RimWorld.Planet.Caravan_PathFollower.StartPath_Patch1 (RimWorld.Planet.Caravan_PathFollower,int,RimWorld.Planet.CaravanArrivalAction,bool,bool)
RimWorld.Planet.CaravanArrivalActionUtility/<>c__DisplayClass0_0`1<RimWar.Planet.CaravanArrivalAction_AttackWarObject>:<GetFloatMenuOptions>b__0 ()
Verse.FloatMenuOption:Chosen (bool,Verse.FloatMenu)
Verse.FloatMenuOption:DoGUI (UnityEngine.Rect,bool,Verse.FloatMenu)
Verse.FloatMenu:DoWindowContents (UnityEngine.Rect)
Verse.FloatMenuWorld:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

IncidentWorker_CaravanMeeting could not generate any pawns.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
RimWar.Utility.IncidentWorker_WarObjectMeeting:TryExecuteWorker (RimWorld.IncidentParms)
RimWar.Utility.IncidentWorker_WarObjectMeeting:PreExecuteWorker (RimWorld.IncidentParms,RimWar.Planet.WarObject,int)
RimWar.Planet.IncidentUtility:DoCaravanAttackWithPoints (RimWar.Planet.WarObject,RimWorld.Planet.Caravan,RimWar.RimWarData,RimWorld.PawnsArrivalModeDef,RimWorld.PawnGroupKindDef)
RimWar.Planet.WarObject:EngageCaravan (RimWorld.Planet.Caravan)
RimWar.Planet.CaravanArrivalAction_AttackWarObject:Arrived (RimWorld.Planet.Caravan)
RimWorld.Planet.Caravan_PathFollower:PatherArrived ()
(wrapper dynamic-method) RimWorld.Planet.Caravan_PathFollower:RimWorld.Planet.Caravan_PathFollower.StartPath_Patch1 (RimWorld.Planet.Caravan_PathFollower,int,RimWorld.Planet.CaravanArrivalAction,bool,bool)
RimWorld.Planet.CaravanArrivalActionUtility/<>c__DisplayClass0_0`1<RimWar.Planet.CaravanArrivalAction_AttackWarObject>:<GetFloatMenuOptions>b__0 ()
Verse.FloatMenuOption:Chosen (bool,Verse.FloatMenu)
Verse.FloatMenuOption:DoGUI (UnityEngine.Rect,bool,Verse.FloatMenu)
Verse.FloatMenu:DoWindowContents (UnityEngine.Rect)
Verse.FloatMenuWorld:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

Interacting with a friendly caravan leads to the same 2 errors with same cause

Exception while generating pawn group: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at BiomesCore.Patches.PawnGroupKindWorker_Trader_GenerateCarriers.GetExtendedCarriers (System.Collections.Generic.List`1[T] originalCarriers, RimWorld.PawnGroupMakerParms parms) [0x000f7] in <afad0cf4ff2c4e1c82dc8c076b79b6d8>:0 
  at (wrapper dynamic-method) RimWorld.PawnGroupKindWorker_Trader.RimWorld.PawnGroupKindWorker_Trader.GenerateCarriers_Patch0(RimWorld.PawnGroupKindWorker_Trader,RimWorld.PawnGroupMakerParms,RimWorld.PawnGroupMaker,Verse.Pawn,System.Collections.Generic.List`1<Verse.Thing>,System.Collections.Generic.List`1<Verse.Pawn>)
  at RimWorld.PawnGroupKindWorker_Trader.GeneratePawns (RimWorld.PawnGroupMakerParms parms, RimWorld.PawnGroupMaker groupMaker, System.Collections.Generic.List`1[T] outPawns, System.Boolean errorOnZeroResults) [0x00223] in <95de19971c5d40878d8742747904cdcd>:0 
  at RimWorld.PawnGroupKindWorker.GeneratePawns (RimWorld.PawnGroupMakerParms parms, RimWorld.PawnGroupMaker groupMaker, System.Boolean errorOnZeroResults) [0x00011] in <95de19971c5d40878d8742747904cdcd>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
RimWorld.PawnGroupKindWorker:GeneratePawns (RimWorld.PawnGroupMakerParms,RimWorld.PawnGroupMaker,bool)
RimWorld.PawnGroupMaker:GeneratePawns (RimWorld.PawnGroupMakerParms,bool)
RimWorld.PawnGroupMakerUtility/<GeneratePawns>d__2:MoveNext ()
System.Collections.Generic.List`1<Verse.Pawn>:.ctor (System.Collections.Generic.IEnumerable`1<Verse.Pawn>)
System.Linq.Enumerable:ToList<Verse.Pawn> (System.Collections.Generic.IEnumerable`1<Verse.Pawn>)
RimWar.Utility.IncidentWorker_WarObjectMeeting:GenerateCaravanPawns (RimWorld.Faction,int)
RimWar.Utility.IncidentWorker_WarObjectMeeting:TryExecuteWorker (RimWorld.IncidentParms)
RimWar.Utility.IncidentWorker_WarObjectMeeting:PreExecuteWorker (RimWorld.IncidentParms,RimWar.Planet.WarObject,int)
RimWar.Planet.IncidentUtility:DoCaravanTradeWithPoints (RimWar.Planet.WarObject,RimWorld.Planet.Caravan,RimWar.RimWarData,RimWorld.PawnsArrivalModeDef)
RimWar.Planet.WarObject:EngageCaravan (RimWorld.Planet.Caravan)
RimWar.Planet.CaravanArrivalAction_EngageWarObject:Arrived (RimWorld.Planet.Caravan)
RimWorld.Planet.Caravan_PathFollower:PatherArrived ()
(wrapper dynamic-method) RimWorld.Planet.Caravan_PathFollower:RimWorld.Planet.Caravan_PathFollower.StartPath_Patch1 (RimWorld.Planet.Caravan_PathFollower,int,RimWorld.Planet.CaravanArrivalAction,bool,bool)
RimWorld.Planet.CaravanArrivalActionUtility/<>c__DisplayClass0_0`1<RimWar.Planet.CaravanArrivalAction_EngageWarObject>:<GetFloatMenuOptions>b__0 ()
Verse.FloatMenuOption:Chosen (bool,Verse.FloatMenu)
Verse.FloatMenuOption:DoGUI (UnityEngine.Rect,bool,Verse.FloatMenu)
Verse.FloatMenu:DoWindowContents (UnityEngine.Rect)
Verse.FloatMenuWorld:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

IncidentWorker_CaravanMeeting could not generate any pawns.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
RimWar.Utility.IncidentWorker_WarObjectMeeting:TryExecuteWorker (RimWorld.IncidentParms)
RimWar.Utility.IncidentWorker_WarObjectMeeting:PreExecuteWorker (RimWorld.IncidentParms,RimWar.Planet.WarObject,int)
RimWar.Planet.IncidentUtility:DoCaravanTradeWithPoints (RimWar.Planet.WarObject,RimWorld.Planet.Caravan,RimWar.RimWarData,RimWorld.PawnsArrivalModeDef)
RimWar.Planet.WarObject:EngageCaravan (RimWorld.Planet.Caravan)
RimWar.Planet.CaravanArrivalAction_EngageWarObject:Arrived (RimWorld.Planet.Caravan)
RimWorld.Planet.Caravan_PathFollower:PatherArrived ()
(wrapper dynamic-method) RimWorld.Planet.Caravan_PathFollower:RimWorld.Planet.Caravan_PathFollower.StartPath_Patch1 (RimWorld.Planet.Caravan_PathFollower,int,RimWorld.Planet.CaravanArrivalAction,bool,bool)
RimWorld.Planet.CaravanArrivalActionUtility/<>c__DisplayClass0_0`1<RimWar.Planet.CaravanArrivalAction_EngageWarObject>:<GetFloatMenuOptions>b__0 ()
Verse.FloatMenuOption:Chosen (bool,Verse.FloatMenu)
Verse.FloatMenuOption:DoGUI (UnityEngine.Rect,bool,Verse.FloatMenu)
Verse.FloatMenu:DoWindowContents (UnityEngine.Rect)
Verse.FloatMenuWorld:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

**Comment by joseasoler** [comment]
@GitBurner3000 Thank you for the detailed bug report! This has been fixed in development, and will be pushed to Steam soon.

**Comment by GitBurner3000** [comment]
Wow you did that fast, I just tested it and it works! Thanks.

**Comment by joseasoler** [comment]
That is good to know! Thank you for double checking, I am happy it works for you now.
